spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      data-locations: classpath:db/seed-data.sql
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time-zone: UTC
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true